# Generated by Django 4.1.9 on 2023-05-11 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ausgabe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Ausgabe")),
                ("jahr", models.CharField(max_length=50, verbose_name="Jahre")),
                ("num", models.CharField(max_length=50, verbose_name="Nummer")),
                ("lnum", models.CharField(max_length=50, verbose_name="lfd.Nummer")),
            ],
            options={
                "verbose_name": "Ausgabe",
                "verbose_name_plural": "Ausgaben",
            },
        ),
        migrations.CreateModel(
            name="Magazin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Magazin Name")),
            ],
            options={
                "verbose_name": "Magazin",
                "verbose_name_plural": "Magazine",
            },
        ),
        migrations.AddField(
            model_name="ausgabe",
            name="magazin",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.magazin"
            ),
        ),
    ]
