# Generated by Django 4.2.1 on 2023-07-14 10:23
from random import randrange

import factory
from django.db import migrations


def forwards_func(apps, schema_editor):
    City = apps.get_model("app", "City")
    Person = apps.get_model("app", "Person")

    class CityFactory(factory.django.DjangoModelFactory):
        class Meta:
            model = City

        name = factory.Faker("city")

    class PersonFactory(factory.django.DjangoModelFactory):
        class Meta:
            model = Person

        name = factory.LazyAttribute(lambda o: f"{o.first_name} {o.last_name}")
        first_name = factory.Faker("first_name")
        last_name = factory.Faker("last_name")
        dob = factory.Faker("date_of_birth")
        city = factory.SubFactory(CityFactory)

    cities = [CityFactory.build() for _ in range(20)]
    City.objects.bulk_create(cities)
    persons = []
    for _ in range(1000):
        city = cities[randrange(0, 10)]
        persons.append(PersonFactory.build(city=city))
    Person.objects.bulk_create(persons)
    CityFactory.create(name="Nobody Lives Here")


def reverse_func(apps, schema_editor):
    City = apps.get_model("app", "City")
    Person = apps.get_model("app", "Person")
    City.objects.all().delete()
    Person.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
