# Generated by Django 4.2.1 on 2023-05-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ausgabe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Ausgabe")),
                ("jahr", models.CharField(max_length=50, verbose_name="Jahre")),
                ("num", models.CharField(max_length=50, verbose_name="Nummer")),
                ("lnum", models.CharField(max_length=50, verbose_name="lfd.Nummer")),
            ],
            options={
                "verbose_name": "Ausgabe",
                "verbose_name_plural": "Ausgaben",
            },
        ),
    ]
